# Generated by Django 3.0 on 2019-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('status', models.BooleanField(default=0)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='blog')),
                ('description', models.TextField()),
            ],
        ),
    ]
