# Generated by Django 3.0 on 2019-12-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191216_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'students'},
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Students')),
            ],
            options={
                'verbose_name_plural': 'phone',
            },
        ),
    ]
